apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: output-image-hello-world
spec:
  type: image
  params:
    - name: url
      value: <REGISTRY_HOST>/<USERNAME>/<IMAGE_NAME>:<TAG> # ie: quay.io/kubealex/hello-tekton:latest
