apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-test-pipeline
spec:
  resources:
    - name: app-image
      type: image
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    # - name: fetch-source-repository
    #   taskRef:
    #     name: git-clone
    #   workspaces:
    #     - name: output
    #       workspace: shared-workspace
    #   params:
    #     - name: url
    #       value: https://github.com/kubealex/hello-springboot.git
    #     - name: subdirectory
    #       value: ""
    #     - name: deleteExisting
    #       value: "true"
    # - name: maven-run
    #   taskRef:
    #     name: maven
    #   runAfter:
    #     - fetch-source-repository
    #   params:
    #     - name: GOALS
    #       value:
    #         - -DskipTests
    #         - package
    #   workspaces:
    #     - name: maven-settings
    #       workspace: maven-settings
    #     - name: source
    #       workspace: shared-workspace
    # - name: kaniko-build
    #   taskRef:
    #     name: build-kaniko-image
    #   runAfter:
    #     - maven-run
    #   params:
    #     - name: pathToDockerFile
    #       value: Dockerfile
    #   workspaces:
    #     - name: source
    #       workspace: shared-workspace
    #   resources:
    #     outputs:
    #     - name: builtImage
    #       resource: app-image
    - name: fetch-manifests-repository
      taskRef:
        name: git-clone
      # runAfter:
      #   - kaniko-build
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/kubealex/hello-manifests.git
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: ls-ws
      runAfter:
        - fetch-manifests-repository
      taskRef: 
        name: ls-ws
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: kustomize-manifests
      runAfter:
        - fetch-manifests-repository
      taskRef:
        name: kustomize-manifests
      workspaces:
        - name: output
          workspace: shared-workspace
      resources:
        inputs:
          - name: app-image
            resource: app-image
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: maven-test-pipeline-run
spec:
  serviceAccountName: kaniko-sa
  pipelineRef:
    name: maven-test-pipeline
  workspaces:
    - name: maven-settings
      configMap:
        name: custom-maven-settings
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  resources:
  - name: app-image
    resourceRef:
      name: output-image-hello-world
