apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ls-ws
spec:
  workspaces: 
    - name: output
  steps:
    - name: ls
      image: ubuntu
      command:
        - ls
      args:
        - "-latr"
        - "/workspace/output/"
